---
abstract: "Manage a module's machine-readable Changes/CHANGES file"
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: '1.001014'
  Test::Pod: '1.48'
configure_requires:
  Module::Build: '0.4211'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Module-Metadata-Changes
provides:
  Module::Metadata::Changes:
    file: lib/Module/Metadata/Changes.pm
    version: '2.06'
requires:
  Config::IniFiles: '2.66'
  DateTime: '0.66'
  DateTime::Format::HTTP: '0.4'
  DateTime::Format::Strptime: '1.5'
  DateTime::Format::W3CDTF: '0.06'
  HTML::Entities::Interpolate: '1.03'
  HTML::Template: '2.9'
  Hash::FieldHash: '0.1'
  Perl6::Slurp: '0.03'
  version: '0.82'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '2.06'
