---
abstract: "Manage a module's CHANGES file"
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.96
  Test::Pod: 1.41
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Metadata-Changes
provides:
  Module::Metadata::Changes:
    file: lib/Module/Metadata/Changes.pm
    version: 2.01
requires:
  Config::IniFiles: 2.66
  DateTime: 0.66
  DateTime::Format::HTTP: 0.4
  DateTime::Format::Strptime: 1.5
  DateTime::Format::W3CDTF: 0.06
  HTML::Entities::Interpolate: 1.03
  HTML::Template: 2.9
  version: 0.82
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 2.01
